# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eeb4b27cd2d0c9018ebef0fc5e9cb8f27ec07b1f64317bb6ad190dbf6e6cf28e24f9a07b522ab353ccf38bd43866c9eb6904e6da4649b4990d60afca91749fca

test:
  secret_key_base: 398f6ecdbf4486c5f5237611b595c6525321683f4d40957fea2307bbe4dd8888d71d8fa4f899309915e69dfd2bdc5c1cf0cc731fe91bb61236b59d6615b26437

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
